### PR TITLE
Fix - Unexpected token: name (agent)

### PR DESCRIPTION
**Pull request by TiBianMod**
This pull request fixes a error from UglifyJs when you preparing the build for production. 

```
"Unexpected token: name (agent) [./node_modules/piwik-tracker/index.js:16,0]"
```

### CODE REVIEW

**Comment by koellcode** [comment]
can someone with write access merge this? would love to see this on master, having also uglifyjs issues :/

**Comment by fhemberger** [comment]
I still don't know why everybody seems to use server components on the client, but as you wish.
¯\_(ツ)_/¯

**Comment by fhemberger** [comment]
Published as `piwik-tracker@1.1.2`, thanks for your contribution! 😀

**Comment by TiBianMod** [comment]
Glad to contribute @fhemberger

> I still don't know why everybody seems to use server components on the client, but as you wish.

@fhemberger let me give you one example please.

Let say we have a SPA with a back end like php or something.

now in this case the back-end don't have any idea which page the client is, so make sense to use something like piwik-tracker to make 1 request to inform the piwik app.

otherwise you need to make a request to the back-end each time the client navigate to a new page and the back-end to make another request to inform the piwik app, so in this case we have 2 request.

So i think make sense for someone wants to use piwik-tracker on the client side for easy use.

So I hope this scenario make sense, and you agree :)

Personally I use the second option by making a request to my back-end, so I don't have to deal with plugins like ad-block etc.

**Comment by fhemberger** [comment]
A simple object serializer like https://stackoverflow.com/a/1714899/409030 and

```js
fetch(this.trackerUrl + '?' + serialize(options))
     .then(…)
```

should basically be enough for the frontend. 😉

**Comment by TiBianMod** [comment]
hehe yes I now, something like this is what I do now :)

**Pull request merged**
